---

- name: Install OpenVPN
  apt: 
    name: openvpn

- name: Ensure base directory exists
  file:
    path: "{{ openvpn_client_base_dir }}"
    state: directory

- include_tasks: create_client.yml
  with_items: "{{ openvpn_client_instances }}"
  loop_control:
    loop_var: openvpn_client
