---

- name: Install OpenVPN
  apt:
    name: openvpn

- name: Create drop-in directory
  file:
    path: /etc/systemd/system/openvpn@.service.d/
    state: directory

- name: Install drop-in unit
  template:
    src: restart.conf.j2
    dest: /etc/systemd/system/openvpn@.service.d/restart.conf
  notify: Reload systemd

- name: Ensure base directory exists
  file:
    path: "{{ openvpn_client_base_dir }}"
    state: directory

- include_tasks: create_client.yml
  with_items: "{{ openvpn_client_instances }}"
  loop_control:
    loop_var: openvpn_client
