---
- name: Install openvpn
  apt: 
    name: openvpn

- name: Slurp openvpn config
  slurp:
    src: "{{ hostvars[openvpn_client_server].openvpn_base_dir }}/{{ openvpn_client_name }}-{{ openvpn_client_server }}.ovpn"
  register: openvpn_config_file
  delegate_to: "{{ openvpn_client_server }}"
  when: openvpn_client_server is defined

- name: Copy OpenVPN config to host 
  copy:
    content: "{{ openvpn_config_file['content'] | b64decode }}"
    dest: "/etc/openvpn/{{ openvpn_client_name }}-{{ openvpn_client_server }}.conf"
  when: openvpn_client_server is defined
  notify: Restart openvpn service

- name: Copy OpenVPN config to host 
  copy:
    src: "files/{{ inventory_hostname }}/{{ openvpn_client_config_file_name }}"
    dest: "/etc/openvpn/{{ openvpn_client_name }}.conf"
  when: openvpn_client_server is not defined
  notify: Restart openvpn service

