---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart OpenVPN service
  service:
    name: "openvpn@{{ openvpn_client_config_identifier }}"
    enabled: yes
    state: restarted
